version: '3.8'

services:
  builder:
    image: builder
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    ports:
      - 8080:8080
    networks:
      - public
      - private

networks:
  public:
  private: