name: Docker Image Pull Request CI

on:
  pull_request:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the PRODUCTION Docker image
        run: docker-compose build .
